awesome books es6, linters, luxon
King-Benx/awesome-books-es6 pull request #1
Opened 2023-02-21 09:23 UTC by King-Benx

**Description:**
This delivers the awesome book project with es6 modules.

**Extra project requirements**
- Time functionality with luxon

**How to run**
1. Clone the project ```git clone git@github.com:King-Benx/awesome-books-es6.git```
2. Checkout to the root directory.
3. Install dependencies ```npm i```
4. Right click your index file and open with live server

**Screenshots**
![Screenshot 2023-02-21 at 12-20-59 Awesome Books](https://user-images.githubusercontent.com/17830204/220303095-7d9d0e7d-a265-4297-bddb-644bd9f99e97.png)
![Screenshot 2023-02-21 at 12-22-05 Awesome Books](https://user-images.githubusercontent.com/17830204/220303121-63203040-09b1-4258-ad0c-6baf45d6a529.png)
![Screenshot 2023-02-21 at 12-22-15 Awesome Books](https://user-images.githubusercontent.com/17830204/220303139-a29129f3-d577-4fce-9f4e-5fb493c11b4e.png)

2023-02-21 09:42 UTC, brainconnect93 requested changes
## STATUS: Changes Required :recycle:

### Hi @King-Benx, 👋 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif">

### To Highlight :1st_place_medal: 
-  Has a proper Pull Request. ✔️  
- No Linter errors :heavy_check_mark: 
- Good use of Github flow ✔️ 

### Changes Required

- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-21 09:42 UTC, brainconnect93 commented on modules/Book.js
> +    this.updateStorage(updatedData);
- [ ] Great effort working on the awesome book project 👍 , but currently, in your project, I noticed I could not add or remove books, anytime a user tries to add a book using the form in the `Add New` section it's not adding and in the `List` section it's not displaying any added book which makes it difficult to remove a book from the list. Kindly fix this.
- [ ] Also in the `List` section you should not have a form asking us to add a book. the `List` is only meant to show the books we have added from the `Add New` section and also the `List` section gives room to remove any book added. Kindly remove the form.

2023-02-21 11:40 UTC, King-Benx commented on modules/Book.js
> +    this.updateStorage(updatedData);
Clear your localstorage and try again

2023-02-24 05:30 UTC, emmiiorji approved these changes
Hi @King-Benx, 

# Status: Approved ✅

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<div align='center'>
<img src='https://user-images.githubusercontent.com/20554583/220871050-9893fe6a-46a0-42a3-8a44-46ac0f7f1154.gif'/>
</div>

## Good Highlights✔️

- Linter checks are passing
- Good commit messages
- Proper use of GitHub flow


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-24 05:32 UTC, merged